version: "3"

services:

  # webserver
  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-nginx'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - ./laravel:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - limitless

  # php
  php-fpm:
    build:
      dockerfile: docker/php/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-php'
    volumes:
      - ./laravel:/var/www/html
    networks:
      - limitless

  # mysql
  mysql:
    build:
      dockerfile: docker/mysql/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "6033:3306"
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    networks:
      limitless:
        aliases:
          - mysql

  # phpmyadmin
  phpmyadmin:
    build:
      dockerfile: docker/phpmyadmin/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8085:80"
    networks:
      limitless:
        aliases:
          - phpmyadmin

networks:
  limitless:
    driver: bridge
