services:

  # webserver
  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-nginx'
    ports:
      - '8080:80'
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - limitless

  # php
  php-fpm:
    build:
      dockerfile: docker/php/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-php'
    volumes:
      - ./laravel:/var/www/html
    networks:
      - limitless

networks:
  limitless:
    driver: bridge
