version: "3"

services:

  # webserver
  nginx:
    build:
      dockerfile: docker/dockerfiles/nginx/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-nginx'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      # Laravel Project files placed in the Nnginx Public Folder
      - ./laravel:/var/www/html
      # Custom Configuration replaces Nginx Default Configuration
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
      # Expose Nginx logs to host machine
      - ./docker/volumes/nginx:/var/log/nginx
    links:
      - php-fpm
    networks:
      - limitless

  # php
  php-fpm:
    build:
      dockerfile: docker/dockerfiles/php/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-php'
    entrypoint: /php-fpm-entrypoint.sh
    volumes:
      - ./laravel:/var/www/html
      - ./docker/entrypoint/php-fpm-entrypoint.sh:/php-fpm-entrypoint.sh
    networks:
      - limitless

networks:
  limitless:
    driver: bridge
