services:

  # Nginx Web Server
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # PHP 8
  php-fpm:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html
